baseURL = 'https://lachlans7.com/'
languageCode = 'en-us'
title = "LachlanS7's Blog"
theme = 'github-style'
relativeURLs = false
canonifyURLs = false

googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "LachlanS7"
  description = "Mathematics and Physics Student"
  github = "LachlanS7"
  linkedin = "lachlan_schilling"
  email = "lwschill73@gmail.com"
  url = "https://lachlans7.com"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/images/github.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/GitHub-Mark-Light-32px.png"
  location = "Australia"
  enableGitalk = true
  math = true

  [params.gitalk]
    clientID = ""
    clientSecret = ""
    repo = "blog"
    owner = "LachlanS7"
    admin = "LachlanS7"
    #id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false

  [[params.links]]
    title = "Link1"
    href = "https://lachlans7.com"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
